### ISSUE TITLE
Need 2 .exe files to have a reverse_tcp connection

### ISSUE THREAD

**Issue by DungLeMTA** [superzerosec/evilpdf#1]
I realize that: 
1. Firstly, victim open file malicious pdf and we have an automatic download .exe file
2. Secondly, victim must run .exe file above to download an other .exe file (ncat.exe) and it will set up a reverse_tcp connection to attacker.
I think it's so complicated. Can we improve it ?

**Comment by superzerosec** [comment]
Sure can. You are most welcome for pull request.
